version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-hello-again:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello again"
          command: "echo Hello, World again!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-hello-again:
        requires:
          - say-hello
